import { type InferInsertModel } from "drizzle-orm";

import { products } from "./schema/commerce";

export const demoCatalogProducts = [
  {
    id: "prod_orange_juice_small",
    slug: "orange-juice-small-8oz",
    name: "Orange Juice",
    description: "Fresh orange juice in an 8oz cup.",
    category: "juice",
    sizeLabel: "small",
    priceCents: 300,
  },
  {
    id: "prod_orange_juice_medium",
    slug: "orange-juice-medium-16oz",
    name: "Orange Juice",
    description: "Fresh orange juice in a 16oz cup.",
    category: "juice",
    sizeLabel: "medium",
    priceCents: 500,
  },
  {
    id: "prod_orange_juice_large",
    slug: "orange-juice-large-32oz",
    name: "Orange Juice",
    description: "Fresh orange juice in a 32oz cup.",
    category: "juice",
    sizeLabel: "large",
    priceCents: 800,
  },
  {
    id: "prod_pineapple_juice_small",
    slug: "pineapple-juice-small-8oz",
    name: "Pineapple Juice",
    description: "Fresh pineapple juice in an 8oz cup.",
    category: "juice",
    sizeLabel: "small",
    priceCents: 300,
  },
  {
    id: "prod_pineapple_juice_medium",
    slug: "pineapple-juice-medium-16oz",
    name: "Pineapple Juice",
    description: "Fresh pineapple juice in a 16oz cup.",
    category: "juice",
    sizeLabel: "medium",
    priceCents: 500,
  },
  {
    id: "prod_pineapple_juice_large",
    slug: "pineapple-juice-large-32oz",
    name: "Pineapple Juice",
    description: "Fresh pineapple juice in a 32oz cup.",
    category: "juice",
    sizeLabel: "large",
    priceCents: 800,
  },
  {
    id: "prod_lemonade_small",
    slug: "lemonade-small-8oz",
    name: "Lemonade",
    description: "Fresh lemonade in an 8oz cup.",
    category: "juice",
    sizeLabel: "small",
    priceCents: 300,
  },
  {
    id: "prod_lemonade_medium",
    slug: "lemonade-medium-16oz",
    name: "Lemonade",
    description: "Fresh lemonade in a 16oz cup.",
    category: "juice",
    sizeLabel: "medium",
    priceCents: 500,
  },
  {
    id: "prod_lemonade_large",
    slug: "lemonade-large-32oz",
    name: "Lemonade",
    description: "Fresh lemonade in a 32oz cup.",
    category: "juice",
    sizeLabel: "large",
    priceCents: 800,
  },
  {
    id: "prod_strawberry_lemonade_small",
    slug: "strawberry-lemonade-small-8oz",
    name: "Strawberry Lemonade",
    description: "Fresh strawberry lemonade in an 8oz cup.",
    category: "juice",
    sizeLabel: "small",
    priceCents: 325,
  },
  {
    id: "prod_strawberry_lemonade_medium",
    slug: "strawberry-lemonade-medium-16oz",
    name: "Strawberry Lemonade",
    description: "Fresh strawberry lemonade in a 16oz cup.",
    category: "juice",
    sizeLabel: "medium",
    priceCents: 525,
  },
  {
    id: "prod_strawberry_lemonade_large",
    slug: "strawberry-lemonade-large-32oz",
    name: "Strawberry Lemonade",
    description: "Fresh strawberry lemonade in a 32oz cup.",
    category: "juice",
    sizeLabel: "large",
    priceCents: 825,
  },
  {
    id: "prod_hotdog",
    slug: "hotdog",
    name: "Hotdog",
    description: "Classic hotdog, grilled and ready to go.",
    category: "hotdog",
    sizeLabel: null,
    priceCents: 300,
  },
  {
    id: "deal_two_small_juices",
    slug: "deal-two-juices-8oz-for-5",
    name: "2 Juices (8oz) for $5",
    description: "Any two small 8oz juices for a bundle price.",
    category: "deal",
    sizeLabel: null,
    priceCents: 500,
    bundleDetails: JSON.stringify({ juices: 2, size: "small" }),
  },
  {
    id: "deal_two_juices_any",
    slug: "deal-two-juices-any-for-6",
    name: "2 Juices (Any) for $6",
    description: "Any two juices for a bundle price.",
    category: "deal",
    sizeLabel: null,
    priceCents: 600,
    bundleDetails: JSON.stringify({ juices: 2, size: "any" }),
  },
  {
    id: "deal_two_hotdogs_one_juice",
    slug: "deal-two-hotdogs-one-juice-for-8",
    name: "2 Hotdogs + 1 Juice for $8",
    description: "Two hotdogs and one juice bundled together.",
    category: "deal",
    sizeLabel: null,
    priceCents: 800,
    bundleDetails: JSON.stringify({ hotdogs: 2, juices: 1 }),
  },
] satisfies Array<InferInsertModel<typeof products>>;
